site_name: Plant DNA LLMs Docs
docs_dir: './en'
# site_dir: '../../generated/en'
# site_url: 'https://placeholder.docs/en/'

theme:
  name: material
  language: en
  features:
    - navigation.tabs
# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Chinese
#       link: /zh/
#       lang: zh
plugins:
  - search:
      lang: en

repo_url: https://github.com/zhangtaolab/Plant_DNA_LLMs

nav:
  - Home: index.md
  - Getting Started:
    - Environment: environment.md
    - 'Fine tune': fine_tune.md
    - Inference: inference.md
    - 'Docker implementation for model inference': docker_implementation_for_model_inference.md
  - Resources:
    - 'Pretrain models': resources/pretrain_models.md
    - 'Fine tune models': resources/finetune_models.md
    - 'Platforms': resources/platforms.md
